### ISSUE TITLE
Maybe switch to JavaScript Version of markdownlint

### ISSUE THREAD

**Issue by neumantm** [Simulation-Software-Engineering/Lecture-Material#119]
> I think this is the time to discuss whether one migrates to the JavaScript version of the linter for the repository. 

_Originally posted by @ajaust in https://github.com/Simulation-Software-Engineering/Lecture-Material/issues/113#issuecomment-1286767847_

The JavaScript Version of markdownlint can be found at <https://github.com/DavidAnson/markdownlint>

**Comment by uekerman** [comment]
@neumantm Thanks for the contribution in #113 already.

I agree with @ajaust statement that having both variants could be an additional burden in the long run.
Or is there a good reason why we would need both?

As I understand one advantage of the JavaScript version is the vscode support. Are there more advantages? Is there any disadvantage we get by changing?

**Comment by neumantm** [comment]
I see one reason for keeping the ruby based markdownlint (in addition or exclusively): Existing contributors do not need to install a new software.
An additional benefit of the JavaScript version is, that it seems to be the more active and more used project at this point.

**Comment by MakisH** [comment]
We currently use https://github.com/marketplace/actions/markdownlint-mdl-action, which uses 

The suggestion is to migrate to https://github.com/DavidAnson/markdownlint, which is a JavaScript re-implementation of https://github.com/markdownlint/markdownlint (which is written in Ruby). The two projects are not related: the Ruby project influenced the JavaScript project.

In other projects, I so far only had experiences with the JavaScript variant, for example in the [preCICE website](https://github.com/precice/precice.github.io/blob/master/.pre-commit-config.yaml), which sets a pre-commit hook that calls https://github.com/igorshubovych/markdownlint-cli.

So far, I do not see any particular reason to choose the one over the other, and the current system seems to work. As for JavaScript vs Ruby, I would argue that both are typically new to this audience.

Indeed, the JavaScript version is newer and seems to be more actively maintained.

Closing for now to keep an overview of what else we need to work on. Please reopen if we should have another look.
