### ISSUE TITLE
PyPI exercise: installing matplotib as a dependency via test.pypi.org fails

### ISSUE THREAD

**Issue by 991jo** [Simulation-Software-Engineering/Lecture-Material#120]
When installing a package via test.pypi.org all dependencies are also resolved via test.pypi.org.

If the requirements contain matplotlib the installation fails because matplotlib has only 1 release on test.pypi.org which is only a binary release packaged for Mac OSX in 2018. See https://test.pypi.org/project/matplotlib/2.2.3/#files

The quick and dirty fix would be to remove matplotlib from the dependencies and install it manually from pypi.org.

**Comment by 991jo** [comment]
Having matplotlib in the dependencies works, if the dependency is already fulfilled beforehand. So first installing matplotlib from the main pypi repo and then installing the package from test.pypi.org.

**Comment by kis-balazs** [comment]
@991jo your solution is not really a solution, since you suppose that the user has to know that they need matplotlib :D

**Comment by 991jo** [comment]
This is a "workaround" because test.pypi.org is not maintained by every package author.

**Comment by kis-balazs** [comment]
Indeed it is, it should be alright I'd assume too :)

**Comment by IshaanDesai** [comment]
Resolved in https://github.com/Simulation-Software-Engineering/Lecture-Material/commit/835b3aea6388e464d5c83ed2b1b77510d9462d08
