### ISSUE TITLE
virtualmachines_slides: UI think Proxmox VE is not really a type 1 hypervisor

### ISSUE THREAD

**Issue by neumantm** [Simulation-Software-Engineering/Lecture-Material#134]
In the [virtualization slides line 55](https://github.com/Simulation-Software-Engineering/Lecture-Material/blob/cfb634569154f59bc142940d507dfba614e90ef6/02_virtualization_and_containers/virtualmachines_slides.md?plain=1#L55) Proxmox VE is mentioned as an example for a type 1 hypervisor.

I don't think this is really true. Proxmox runs on a debian operating system. It is just that they distribute their software together with the operating system as one ISO. However, it is also possible to manually install Proxmox VE on an existing debian-based linux installation.
More importantly, after the installation the admin can easily login to the linux system of the host and manually perform any changes like on any other linux system. It even allows to fully configure proxmox without the UI, by editing the relvant configuration files.  

I think proxmox VE is really a type 2 hypervisor.

**Comment by IshaanDesai** [comment]
Further discussed in https://github.com/Simulation-Software-Engineering/Lecture-Material/pull/136
