### ISSUE TITLE
Issue with containers task

### ISSUE THREAD

**Issue by MohamedAdelNaguib** [Simulation-Software-Engineering/Lecture-Material#144]
Hello , 
I have an issue when trying to apply ``` vegrant up ``` . It gives me this error

<img width="593" alt="Screenshot 2022-11-21 at 02 11 23" src="https://user-images.githubusercontent.com/47299025/202938022-ff7b80d6-2ab2-4153-9714-7a3c860b6dcb.png">

 and I tried to solve it with different ways but without any result.
If anyone has faced this error or have a solution please share it.
I also tried it on linux and windows and it gave me the same error. 

Thanks in advane.

**Comment by MarkAshraf96** [comment]
I tried on macOS 13, and I had the same error. :')

**Comment by IshaanDesai** [comment]
@MohamedAdelNaguib from the error message I can predict that something went wrong with the configuration and not something with Vagrant itself (it also says that at the end of the error message). Can you try to revert all the configuration steps you added to the Vagrantfile and just try to launch a basic Ubuntu container? That would already give us a clue on what is going wrong.

**Comment by MohamedAdelNaguib** [comment]
@IshaanDesai Thanks for your reply ! I found out the reason behind the problem and how to solve it.  Basically, the image we are using to make sure that vagrant is working fine ```hashicorp/bionic64``` is created with only 1 cpu which is not sufficient for ubuntu kernel to work so the kernel go into a panic state. so you need to increase the number of cores of the virtual machine either by doing it on the GUI of virtualBox or by editing in the vagrnatfile.

**Comment by sumanth0703** [comment]
@MohamedAdelNaguib I had the same problem and even after increasing the number of cores, It's still not working. Did you change anything else for it to work?

**Comment by MohamedAdelNaguib** [comment]
@sumanth0703 I have a couple of questions , I just increased number of cpus maybe try to increase it more than 2. And there are some errors in displayed in the virtualBox itself you can fix it like the GPU memory is not enough.

**Comment by IshaanDesai** [comment]
>  so you need to increase the number of cores of the virtual machine either by doing it on the GUI of virtualBox or by editing in the vagrnatfile. Note : This solution works on windows.

Good to know that you found the fix! I will add a note about this in the exercise sheet.

**Comment by IshaanDesai** [comment]
> @IshaanDesai Thanks for your reply ! I found out the reason behind the problem and how to solve it. Basically, the image we are using to make sure that vagrant is working fine `hashicorp/bionic64` is created with only 1 cpu which is not sufficient for ubuntu kernel to work so the kernel go into a panic state. so you need to increase the number of cores of the virtual machine either by doing it on the GUI of virtualBox or by editing in the vagrnatfile. Note : This solution works on windows.

Marking this as a solution for this issue.
