### ISSUE TITLE
Compatibility issues in virtual machines and container exercise

### ISSUE THREAD

**Issue by arora-vidushi** [Simulation-Software-Engineering/Lecture-Material#145]
For [virtual machines and containers exercise](https://github.com/Simulation-Software-Engineering/Lecture-Material/blob/main/02_virtualization_and_containers/virtualmachines_containers_exercise.md), 

[VirtualBox task](https://github.com/Simulation-Software-Engineering/Lecture-Material/blob/main/02_virtualization_and_containers/virtualmachines_containers_exercise.md#tasks-virtualbox) has compatiblity issues with M1 devices. The software is currently in beta version for M1 devices and it gives CPU error when trying to power on a VM.  

This compatibility issue also causes problem for [Vagrant task](https://github.com/Simulation-Software-Engineering/Lecture-Material/blob/main/02_virtualization_and_containers/virtualmachines_containers_exercise.md#tasks-vagrant) which uses VirtualBox. 

Some points about [Parallels](https://www.parallels.com/eu/) for alternative solution : 

- It has trial version for 2 weeks period and user need to pay to use after that.
- It runs windows on Mac which lets user run any windows application in Parallels application. 

Any other alternative is not explored yet.

**Comment by IshaanDesai** [comment]
Thanks for opening the issue and recording your findings. Can you also put in the actual error output you get when trying to work with VirtualBox on the M1 machine? This would give a better understanding of what is actually going wrong.

Did you try to use Parallels for the exercise? In principle a two week trial period should be sufficient for this exercise.

**Comment by ajaust** [comment]
Only slighly related. If you have problems with Docker images at some point, you can try to add `--platform linux/amd64` to the `docker CMD`, so for example `docker run --platform linux/amd64 OTHERCOMMANDS` and/or `docker build --platform linux/amd64 OTHERCOMMANDS`, see also the [Docker forum](https://forums.docker.com/t/run-x86-intel-and-arm-based-images-on-apple-silicon-m1-macs/117123/3). It also helps in case the image itself works, but software you want to install inside the container. I ran into some Python packages that do no supply an arm64 wheel which means that installation via `pip` failed.

Using the `platform` options runs the actual Linux-based image via emulation if I remember correctly. The emulation is usually slower than native Arm-based containers, but I think this should be fine for the exercises of this lecture.

**Comment by ajaust** [comment]
Also https://github.com/Simulation-Software-Engineering/Lecture-Material/issues/144 could be  related to your issue. Could you try if setting the number of CPUs to 2 or more fixes the issue for you? All the news about the VirtualBox beta are quite positive that VirtualBox should work quite well. I cannot test it myself though. :disappointed:

**Comment by arora-vidushi** [comment]
Hello @IshaanDesai 

This is the error message:
```
Unsupported CPU. (VERR_UNSUPPORTED_CPU).
Result Code:
NS_ERROR_FAILURE (0X80004005)
Component:
ConsoleWrap
Interface:
IConsole {6ac83d89-6ee7-4e33-8ae6-b257b2e81be8}
``` 

Snippet of [VBox.log](https://github.com/Simulation-Software-Engineering/Lecture-Material/files/10099397/VBox.log):

```
00:00:01.248055 VERR_UNSUPPORTED_CPU (-1002) - Unsupported CPU.
00:00:01.248400 VMSetError: /Users/vbox/tinderbox/mac-rel/src/VBox/VMM/VMMR3/VM.cpp(336) int VMR3Create(uint32_t, PCVMM2USERMETHODS, PFNVMATERROR, void *, PFNCFGMCONSTRUCTOR, void *, PVM *, PUVM *); rc=VERR_UNSUPPORTED_CPU
00:00:01.248402 VMSetError: Unsupported CPU.
00:00:01.248698 ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={6ac83d89-6ee7-4e33-8ae6-b257b2e81be8} aComponent={ConsoleWrap} aText={Unsupported CPU. (VERR_UNSUPPORTED_CPU)}, preserve=false aResultDetail=-1002
00:00:01.248767 Console: Machine state changed to 'PoweredOff'
00:00:01.249443 Power up failed (vrc=VERR_UNSUPPORTED_CPU, rc=NS_ERROR_FAILURE (0X80004005))
```
Unfortunately, due to time constraints, I did not troubleshoot it much. @ajaust It fails even after the number of CPUs is 2.
But I will give troubleshooting another go this week or after and will update here if I find some solution that can resolve this issue. 


I did not use Parallels for the exercise. The app installs Windows and we need to work inside that app as I would on any other Windows PC. Due to several constraints, I chose to directly use a friend's Windows laptop to perform the exercise task. But I can work on it again using Parallels and update my experience.

**Comment by ajaust** [comment]
Thanks for the update. That is very helpful information. :)

I am not sure if VirtualBox would still expect a dedicated ARM image or whether VirtualBox would run the x86_64 emulation in the background.

**Comment by MakisH** [comment]
VirtualBox now (version 7) prominently advertises a Download option for Apple Silicon: https://www.virtualbox.org/wiki/Downloads

Closing for now, please reopen with more details if this is still relevant.
