### ISSUE TITLE
GUI in docker container

### ISSUE THREAD

**Issue by uygarkov** [Simulation-Software-Engineering/Lecture-Material#149]
Hello, 

I installed my assigned simulation software (Firedrake) in the Docker container that developers created. What I wonder is: How can I use GUI, for example, I want to plot a graph of results inside the container. 

I searched online and installed Xming to my computer but whenever I want to access the graphs inside my docker, it prompts me this error: 

Thanks in advance. 
![resim](https://user-images.githubusercontent.com/83709209/203725148-aca61584-cf78-488f-8048-cd9da5a7c781.png)

**Comment by IshaanDesai** [comment]
@uygarkov this issue seems to be specific to your Challenge and not related to the Lecture Material. Let us discuss this separately via email or in presence. I will close this issue now.
