### ISSUE TITLE
Time table is not up-to-date.

### ISSUE THREAD

**Issue by LitschiW** [Simulation-Software-Engineering/Lecture-Material#165]
The [Time Table](https://github.com/Simulation-Software-Engineering/Lecture-Material/blob/main/timetable.md) is only available until December, but should be until February.

**Comment by uekerman** [comment]
Yes, will be updated with the material for this week, latest tomorrow.

**Comment by uekerman** [comment]
A preview already

| Date | Type | Chapter | Topic | Lecturer |
| ---- | ---- | ------- |------ | -------- |
| 12.01. |Lecture | 4 | Documentation Tools | Benjamin |
| 12.01. |Lecture | 6 | Licenses, Versioning, ... | Benjamin |
| 19.01. |Lecture | 5 | Testing in Python | Ishaan |
| 19.01. |Lab | 5 | Testing in Python | Ishaan |
| 26.01. |Lecture | 5 | Automation, CI/CD | Benjamin |
| 26.01. |Lab | 5 | Automation, CI/CD | Benjamin |
| 02.02. |Lecture | 5 | Boost.Test | Benjamin |
| 02.02. |Lab | 5 | Boost.Test | Benjamin |
| 09.02. |Presentations | C | **final student presentations** | students |
| 09.02. |Presentations | C | **final student presentations** | students |
