### ISSUE TITLE
Broken links (organization slides)

### ISSUE THREAD

**Issue by LarissaBrencher** [Simulation-Software-Engineering/Lecture-Material#22]
Hello,

while looking up the slides for the individual challenge introduction, I saw that the links in the overview.md of the organization folder are broken (error 404). I thought that I could maybe fix it and I looked into the overview file, but couldn't find the error in the url, which is why I am opening this issue.
The corresponding links in the time table which link to the organization slides are also broken.

**Comment by LarissaBrencher** [comment]
Found the error in the links (missing "_slides" at the end of the file names

**Comment by IshaanDesai** [comment]
Resolved in https://github.com/Simulation-Software-Engineering/Lecture-Material/pull/23
