### ISSUE TITLE
Assign unique numbering to slides' name

### ISSUE THREAD

**Issue by LarissaBrencher** [Simulation-Software-Engineering/Lecture-Material#24]
Hello,

I think it would be helpful to change the slides' names to a numbered convention, e.g. 01-intro-slides.md
Then it is less confusing when downloading the zipped folder of pdf slides and further, it makes sense to assign each markdown slide set an own number in order for it to be uniquely assigned (and possibly avoid name duplicates). 
(Consequently, all the existing links need to be changed accordingly to the new names, so we don't have broken links again 😃)

**Comment by ajaust** [comment]
Would it be helpful when we add more information to the file names? 

We could generate a prefix or subdirectory from the files' paths. Examples:

- The file in `version-control/material/intro_slides.md` could create an output file named `version-control-intro_slides.pdf`, i.e., it has a prefix that makes the file name longer.
- The file in `version-control/material/intro_slides.md` could create an output file named `version-control/intro_slides.pdf`, i.e., the file is stored in a subdirectory.

**Comment by LarissaBrencher** [comment]
Yes, adding more information to the file names would definitely help! In my opinion the second example with the generated sub-directory would be the better choice (avoids possibly extremely long file names). And it has the advantage that one can just copy the sub-folder with pdfs of the current lecture instead of selecting several files.

**Comment by ajaust** [comment]
I made a first draft for a PR. We can still discuss whether we want to add the numbers to the files. I assume that the current PR does not break any links since we never explicitly link to the PDFs.

**Comment by LarissaBrencher** [comment]
Thanks for resolving this so quickly :)

**Comment by ajaust** [comment]
@uekerman Do you have any preference towards/against additionally numbering the slides? Or with other words: Are you ok with merging the PR?

**Comment by uekerman** [comment]
I understand and agree with the original problem. However, I don't yet like the numbering solution too much. I could see the order of material (which we would then have) changing often in the future.
The folder structure seems to be an easier and less invasive solution :+1:
Thanks for reporting and thanks for solving!
