### ISSUE TITLE
Also allow other box images

### ISSUE THREAD

**Issue by cheriimoya** [Simulation-Software-Engineering/Lecture-Material#34]
I am using libvirt instead of virtualbox for this course and i know of someone using parallels.

So this other person and i are somewhat forced to use the generic box for the assignments. 

However, the requirement is

> Your virtual machine must be based on the ubuntu/focal64 image. See official boxes of Vagrant.

which i cannot satisfy.

![image](https://user-images.githubusercontent.com/28303440/141469176-74b29270-e109-4f76-8762-25298b85bb5e.png)

**Comment by cheriimoya** [comment]
so i will use `generic/ubuntu2004` if that's okay :eyes:

**Comment by ajaust** [comment]
The idea behind having rather strict requirements in the exercise sheet is to give precise guidelines to students who are not so deep into the virtualization topic. Moreover, we cannot test for all virtualization techniques for the exercise so we decided to go for VirtualBox which is well supported on most operating systems.

In general, we could relax this requirement a bit. We could add some note about in the exercise sheet without changing the main part of the exercise. However, if we want to introduce some CI for this exercise in the future it will also become complicated if we want to support different virtualization providers.

I guess part of your comment here would fit better in the GitLab issue of the exercise. :wink:

**Comment by MakisH** [comment]
Handled in #197.
