### ISSUE TITLE
Use font with full Unicode support for PDFs

### ISSUE THREAD

**Issue by ajaust** [Simulation-Software-Engineering/Lecture-Material#40]
I have changed the PDF engine for the PDF creation to `xelatex` in a recent commit (bca7c3c84cea74197f5b8b4252e4b36d51cc84d5). This was necessary to allow for the compilation of the `building-and-packaging/material/packaging_python_slides.md` where special characters are used in code blocks. Now, the PDFs can be created, but many of the special characters do not appear in the created PDFs. The issue is that the standard LaTeX font used does not include all Unicode characters. Therefore, we see also some warnings during the PDF creation as:

```bash
Warning:  Missing character: There is no └ (U+2514) (U+2514) in font [lmsans12-regular]:mapping=te
Warning:  Missing character: There is no ─ (U+2500) (U+2500) in font [lmsans12-regular]:mapping=te
Warning:  Missing character: There is no ─ (U+2500) (U+2500) in font [lmsans12-regular]:mapping=te
Warning:  Missing character: There is no └ (U+2514) (U+2514) in font [lmsans12-regular]:mapping=te
Warning:  Missing character: There is no ─ (U+2500) (U+2500) in font [lmsans12-regular]:mapping=te
Warning:  Missing character: There is no ─ (U+2500) (U+2500) in font [lmsans12-regular]:mapping=te
Warning:  Missing character: There is no ├ (U+251C) (U+251C) in font [lmsans12-regular]:mapping=te
Warning:  Missing character: There is no ─ (U+2500) (U+2500) in font [lmsans12-regular]:mapping=te
Warning:  Missing character: There is no ─ (U+2500) (U+2500) in font [lmsans12-regular]:mapping=te
Warning:  Missing character: There is no └ (U+2514) (U+2514) in font [lmsans12-regular]:mapping=te
```

We should move to another font that has full Unicode support or at least supports the missing characters. Maybe we could/should fix this together with #39.

**Comment by uekerman** [comment]
Maybe a simpler strategy would be to simply remove these "tree" symbols and use normal lists instead.
