### ISSUE TITLE
Rework pip/PyPI lecture

### ISSUE THREAD

**Issue by uekerman** [Simulation-Software-Engineering/Lecture-Material#46]
I had the feeling that we could have fit the content of the pip/PyPI lecture into 60 mins instead of 90 mins.

There were a few redundancies and also a few unnecessary details:

* Motivation could be a bit faster I guess, currently there is also some repetition there.
* LICENSE slide is not necessary (for the moment everybody has some understanding what a license is, later we will give more details).
* README slide is not necessary (same reasoning).
* testpypi was explained twice (though only on slide once I think).

That would give us some additional time in which ...

* We could show an example for conda.
* Explain what the Jupytor project is.

Also, the example on the slides is no real example, it still contains placeholders (e.g. `<package-name>`). Why not doing a real example (as a demo) with some "Hello World" code?

Last point: Sometimes, there were multiple topics on one slide (e.g. the `--user` squeezed on another slide). Let's use one slide per topic.

**Comment by IshaanDesai** [comment]
Some more points regarding the Python packaging lecture:

* Having a demo on how to use `pip` would provide more insight than just talking about it
* The file `setup.cfg` needs to be explained, as mentioned in https://github.com/Simulation-Software-Engineering/Lecture-Material/issues/44
* A Conda demo is also important to supplement the introduction to Conda
* Reworking the quiz, poll and word cloud questions at the start of the lecture
* Explain the `install_dependencies` in `setup.py` in greater detail. For example, explain how specific version requirements for dependencies can also be specified through this functionality
* Explain how to import functionality from other files which works for non-packaged and packaged code
* Explain how Python executable codes can be packaged. Right now the focus is mainly on packaging library-style codes

**Comment by IshaanDesai** [comment]
**Important note**: https://github.com/Simulation-Software-Engineering/Lecture-Material/pull/3 consists of review comments which were not addressed at the time of merging and are valuable for improving the content further.

**Comment by uekerman** [comment]
> Reworking the quiz, poll and word cloud questions at the start of the lecture

Could you describe the problem? Otherwise, you / we will forget what you had in mind.

**Comment by IshaanDesai** [comment]
> Could you describe the problem? Otherwise, you / we will forget what you had in mind.

The comment is mainly related to further refine the quiz by adding more quiz questions than poll or word cloud questions. The poll and word cloud were also informative and should also be there.
