### ISSUE TITLE
Include instructions about how to change the __init__.py for the packaging exercise

### ISSUE THREAD

**Issue by MagnusOstertag** [Simulation-Software-Engineering/Lecture-Material#49]
I had to add an ```import  <username>diffusion2D```statement to __init__.py for the module to work as expected.

**Comment by IshaanDesai** [comment]
Hi @MagnusOstertag, 
An `import` statement in the file `__init__.py` should not be required in this exercise. If you have opened a pull request for submission, can you point me to it? I will have a look at your packaged code then

**Comment by MagnusOstertag** [comment]
This is [my pull request](https://github.com/Simulation-Software-Engineering/Diffusion2D-Python-Package/pull/2).

**Comment by IshaanDesai** [comment]
@MagnusOstertag I see the code and packaging is done as per the requirement. How do you call the function to solve the problem finally? Can you describe it? I think the way you call the function is leading to the need to add the statement in `__init__.py`

**Comment by MagnusOstertag** [comment]
Hi @IshaanDesai, 
@andreichalapco pointed out to me that also according to the [docs](https://docs.python.org/3/distutils/setupscript.html) it can be done without adding code to ```__init__``` by writing ```packages=["<username>diffusion2D"]```.
> you must explicitly list all packages in packages: the Distutils will not recursively scan your source tree looking for any directory with an ```__init__.py``` file.
