### ISSUE TITLE
Reactivate MD010 to check for hard tabs

### ISSUE THREAD

**Issue by ajaust** [Simulation-Software-Engineering/Lecture-Material#52]
I deactivated rule MD010 of markdownlint which checks for hard tabs. We need this at least in the CMake chapter #51 which code blocks of Makefiles which depend on hard tabs.

We should be able to activate this rule again when/if https://github.com/markdownlint/markdownlint/pull/396 gets into markdownlint and there is a new release.

**Comment by MakisH** [comment]
MD010 is still failing. Let's close this issue and reopen if we actually have any concrete reason and something we can do about it.
