### ISSUE TITLE
CPack/Debian Lecture Recording

### ISSUE THREAD

**Issue by jonahaag** [Simulation-Software-Engineering/Lecture-Material#64]
Hi,
will the recording of last weeks lecture on CPack/Debian be uploaded to Ilias? I wasn't able to attend in person and would like to watch the video before starting the exercise. Otherwise, working with the notes/slides would be fine, just wanted to ask if I should wait for another day or so 😄 Thanks in advance!

**Comment by ajaust** [comment]
I am sorry for the delay regarding the video. The video is in the postprocessing pipeline and we have to release it manually afterwards. I added a reminder to check at 13:00 to check whether the postprocessing is finished. I will also add a reminder to trigger the postprocessing earlier.

**Comment by jonahaag** [comment]
Thanks for the quick response! Also, no hurry, I just wanted to make sure there was no issue with the recording and no upload at all as a result thereof

**Comment by ajaust** [comment]
The lecture recordings are now (finally) online so you should be good to go.

We also discussed the feedback form we had on ILIAS in the lecture. At the moment we cannot add the video due to some error message. We will try do add the discussion video during the week.

**Comment by ajaust** [comment]
The discussion is finally online as well. Thanks for reporting the issue. I will close the issue now. Feel free to reopen if something is wrong.
