### ISSUE TITLE
Wrong variable name in CPack lecture (slides & notes)

### ISSUE THREAD

**Issue by LarissaBrencher** [Simulation-Software-Engineering/Lecture-Material#65]
I think that the variable should be CPACK_DEBIAN_PACKAGE_MAINTAINER and not CPACK_PACKAGE_MAINTAINER in the slides and the notes. As I am quite new to CPack I thought that asking here, if my thought is correct, might be the better choice than to just change it and open an PR.

**Comment by ajaust** [comment]
You are right. I am not sure where the `CPACK_PACKAGE_MAINTAINER` came from. I will push a fix.

`CPACK_DEBIAN_PACKAGE_MAINTAINER` is mentioned in the [CMake documentation](https://cmake.org/cmake/help/latest/cpack_gen/deb.html#variable:CPACK_DEBIAN_PACKAGE_MAINTAINER) and it will be derived from `CPACK_PACKAGE_CONTACT` if not set explicitly.

**Comment by ajaust** [comment]
See #66

**Comment by ajaust** [comment]
Thanks for letting us know.
