### ISSUE TITLE
link checker action flags several external links as unaccessible / problematic

### ISSUE THREAD

**Issue by IshaanDesai** [Simulation-Software-Engineering/Lecture-Material#73]
[It is observed](https://github.com/Simulation-Software-Engineering/Lecture-Material/runs/4488410230?check_suite_focus=true) that the linkchecker action fails for several external links. These links either need to be whitelisted or the cause of access failure through a GitHub action needs to be figured out.

**Comment by ajaust** [comment]
I did a quick check and there are several reasons for the failing test. These cases I could observe:

- Links to figures, slides, demos etc. included in this repository which still assume the old repository structure. (seems to be the majority of issues)
- Bad URL/formatting issues of URLs. For example, a homepage moved, incomplete example links, or there was a type in there.
- URLs that forward one to another homepage. Possible solutions
  - Check with parameter `--allow-redirect` that ignores the forwarding/redirecting.
  - Fix the links. I think for most links, there exists a way to write them such that no forwarding/redirecting is triggered.

There might be other/further reasons.

**Comment by IshaanDesai** [comment]
Dummy links which serve the purpose of showing example commands in the slides of the Spack lecture are getting flagged by the link checker action. Examples are `"https://..."`, `https://...archive/refs/tags/v0.3.0.tar.gz`, etc. from [this section](https://github.com/Simulation-Software-Engineering/Lecture-Material/blob/main/03_building_and_packaging/spack_slides.md#common-spack-package-properties-13). Probably the easiest solution here is to whitelist these links. @ajaust would you suggest whitelisting or some other smarter way?

**Comment by ajaust** [comment]
Currently I would consider putting a working link in there. At least in the code blocks hedgedoc allows you to scroll to the side so I would be happy with using a full example there.

**Comment by ajaust** [comment]
As discussed yesterday the link checker now also fails since too many requests are made within the "lecture material" repository. Due to this some check will time out. 

The current plan is to deactivate the link checker action. If possible, we would re-enable the action to run on changed files only or any other useful subset.

**Comment by IshaanDesai** [comment]
The [link checker workflow](https://github.com/Simulation-Software-Engineering/Lecture-Material/actions/workflows/linkchecker.yml) has been disabled temporarily.

**Comment by uekerman** [comment]
We learned from the preCICE website, that this can be a pain to check in CI. Not planned for the moment.
