### ISSUE TITLE
Import GitHub repos

### ISSUE THREAD

**Issue by MagnusOstertag** [Simulation-Software-Engineering/Lecture-Material#89]
When we have to run sth in our own namespace (documentation, actions) the standard instruction is create the repo and then to copy and commit the code from the given repository. However, when creating a new repository GitHub also offers the possibility to 'import a repository'. Imho this is a clearer and easier way and should be the standard instruction.

**Comment by uekerman** [comment]
Sounds interesting, but I am not sure I got it yet. Do you mean the option

> …or import code from another repository
You can initialize this repository with code from a Subversion, Mercurial, or TFS project.

?
You cannot enter a git repo here if I understood it correctly.

**Comment by MagnusOstertag** [comment]
I'm not sure to which option you are referring to, I refer to the second option in the drop-down menu of the plus- symbol ![import_repo](https://user-images.githubusercontent.com/29351595/150764136-b83e050a-145b-4c54-ba90-c1e6fccad2ee.png).
```
Import your project to GitHub
Import all the files, including the revision history, from another version control system.
```

**Comment by ajaust** [comment]
That sounds like a much better solution than what we currently do. I was not aware that this is possible. I did a quick test importing the "Lecture Material" repository and that worked out nicely.

**Comment by ajaust** [comment]
> Sounds interesting, but I am not sure I got it yet. Do you mean the option
> 
> > …or import code from another repository
> > You can initialize this repository with code from a Subversion, Mercurial, or TFS project.
> 
> ? You cannot enter a git repo here if I understood it correctly.

Maybe the documentation is old/incomplete? If I to the import step (see screenshot by @MagnusOstertag) and click on "supported VCS" it says

    We support importing repositories from Git, Subversion, Mercurial, and TFS. Here are some example urls.

    https://example.com/svn/ <= Don’t include trunk or branches
    https://example.com/hg
    https://tfs.example.com/tfs	<= We’ll figure out which project next
